---
- name: Install progs
  hosts: piservers
  remote_user: pi
  become: true
  vars: 
    txt_line: ' ALL=(ALL) NOPASSWD: ALL'
    file_path: /etc/snmp/snmpd.conf

  tasks:
    - name: Install speedtest  (state=present is optional)
      apt:
        name: speedtest-cli
        state: present


    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install snmp packages
      apt:
        name: snmpd
        state: latest
    
    - name: Install snmp packages
      apt:
        name: snmp
        state: latest

    - name: Enable snmp service
      service: name=snmpd enabled=yes
      notify: Restart snmpd

    - name: Set timezone to Europe/Oslo
      community.general.timezone:
        name: Europe/Oslo


    - name: Remove localhost from SNMP Config
      lineinfile:
        path: "{{file_path}}"
        regexp: '^agentAddress  udp:127.0.0.1:161'
        line: '#agentAddress  udp:127.0.0.1:161'
      
    - name: Configure SNMP to listen on all interfaces
      lineinfile:
        path: "{{file_path}}"
        regex: '^#agentAddress udp:161'
        line: 'agentAddress udp:161,udp6:[::1]:161'

    - name: Configure SNMP public community
      lineinfile:
        path: "{{file_path}}"
        insertafter: '^#rocommunity public'
        line: 'rocommunity public 192.168.0.0/16'
 
 
    - name: Configure SNMP syslocation
      lineinfile:
        path: "{{file_path}}"
        regex: '^sysLocation'
        line: 'sysLocation Kirsebærhagen 23, 4055 Sola , Norway'
    
    - name: Configure SNMP syscontact
      lineinfile:
        path: "{{file_path}}"
        regex: '^sysContact'
        line: 'sysContact geir@kvalheim.net'

    - name: Enable snmp service 2
      service: name=snmpd enabled=yes
      notify: Restart snmpd