---
- name: Install progs
  hosts: all
  remote_user: pi
  become: true
  vars: 
    config_file_path: /boot/config.txt
    hdmi_group: 2
    hdmi_mode: 82
    hdmi_safe: 1
    hdmi_hotplug: 1
    gpu_mem: 256

  tasks:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install speedtest  (state=present is optional)
      apt:
        name: speedtest-cli
        state: present

    - name: Install tcpdump  (state=present is optional)
      apt:
        name: tcpdump
        state: present

    - name: Install Cockpit  (state=present is optional)
      apt:
        name: cockpit
        state: present
  
    - name: Install HTOP  (state=present is optional)
      apt:
        name: htop
        state: present


    - name: Install Aptitude  (state=present is optional)
      apt:
        name: aptitude
        state: present

    - name: Install Terminator  (state=present is optional)
      apt:
        name: terminator
        state: present

    - name: Install Traceroute  (state=present is optional)
      apt:
        name: traceroute
        state: present

    - name: Install wget  (state=present is optional)
      apt:
        name: wget
        state: present

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

   

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    
    - name: Set timezone to Europe/Oslo
      community.general.timezone:
       name: Europe/Oslo

    # - name: Enable HDMI in safe mode to (hdmi_safe={{hdmi_safe}})
    #   lineinfile:
    #     path: "{{config_file_path}}"
    #     regexp: '^#hdmi_safe='
    #     line: 'hdmi_safe={{hdmi_safe}}'

    # - name: Force HDMI (hdmi_force_hotplug={{hdmi_hotplug}})
    #   lineinfile:
    #     path: "{{config_file_path}}"
    #     regexp: '^#hdmi_force_hotplug='
    #     line: 'hdmi_force_hotplug={{hdmi_hotplug}}'

    # - name: Set GPU memory (gpu_mem={{gpu_mem}})
    #   lineinfile:
    #     path: "{{config_file_path}}"
    #     regexp: '^gpu_mem='
    #     line: 'gpu_mem={{gpu_mem}}'

    # - name: Set HDMI group (hdmi_group={{hdmi_group}})
    #   lineinfile:
    #     path: "{{config_file_path}}"
    #     regexp: '^hdmi_group='
    #     line: 'hdmi_group{{hdmi_group}}'

    # - name: Set HDMI mode (hdmi_mode={{hdmi_mode}})
    #   lineinfile:
    #     path: "{{config_file_path}}"
    #     regexp: '^hdmi_mode='
    #     line: 'hdmi_mode={{hdmi_mode}