---
- name: Install progs
  hosts: piservers
  remote_user: pi
  become: true
  tasks:
    - name: Install speedtest  (state=present is optional)
      apt:
        name: speedtest-cli
        state: present


    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install snmp packages
      apt:
        name: snmpd
        state: latest

    - name: Enable snmp service
      service: name=snmpd enabled=yes
      notify: Restart snmpd

    - name: Set timezone to Europe/Oslo
      community.general.timezone:
        name: Europe/Oslo