- name: Create Default Users
  hosts: all
  remote_user: pi
  become: true

  vars: 
    user_name: geirkv
    txt_line: ' ALL=(ALL) NOPASSWD: ALL'
    file_path: /etc/sudoers.d/010_"{{user_name}}"-nopasswd
 
  tasks:
    - name: Creat user account and set password
      user: 
        name: "{{user_name}}"
        password: $6$A8arGSOJWtF53jH4$.Pswn4ue2nBio9fRfmqOFz29qJulE/ZDm1CDmL8c0rU7pWki6Rn/Ae5p4V.tF6KudQAGxK567ppLfDg.wzGQc/
        group: sudo
      

    - name: Ensure that the user can elevate to sudo without password
      lineinfile:
        path: "{{file_path}}"
        state: present
        line: '{{user_name + txt_line}}'
        create: yes
