all:
  children:
    piservers:
      hosts:
        PI01.kvalheim.net:
        PI02.kvalheim.net:
        PI03.kvalheim.net:
        PI04.kvalheim.net:
        PI05.kvalheim.net:
        PI06.kvalheim.net:
        PI08.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_ssh_pass: raspberry

    test:
      hosts:
        PI07.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_ssh_pass: raspberry
      
    gcp:
      hosts:
        GCP01.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_ssh_pass: raspberry

    non_crit:
      hosts:
        PI01.kvalheim.net:
        PI02.kvalheim.net:
        PI03.kvalheim.net:
        PI04.kvalheim.net:
        PI08.kvalheim.net:
        GCP01.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_ssh_pass: raspberry
    
    crit:
      hosts:
        PI05.kvalheim.net:
        PI06.kvalheim.net:
        PI07.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_ssh_pass: raspberry