[piservers]
    PI01.kvalheim.net
    PI02.kvalheim.net
    PI03.kvalheim.net
    PI04.kvalheim.net
    PI05.kvalheim.net
    PI06.kvalheim.net
    PI08.kvalheim.net


[piservers:vars]
ansible_connection=ssh
ansible_user=pi
ansible_ssh_pass=raspberry