all:
  children:
    piservers:
      hosts:
        #PI01.kvalheim.net:
        #SEC01.kvalheim.net:
        PI02.kvalheim.net:
        PI03.kvalheim.net:
        PI04.kvalheim.net:
        PI05.kvalheim.net:
        PI06.kvalheim.net:
        PI08.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible

    test:
      hosts:
        PI01.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible

    sec:
      hosts:
        #SEC01.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible
      
    gcp:
      hosts:
        #GCP01.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible

    non_crit:
      hosts:
        PI01.kvalheim.net:
        PI02.kvalheim.net:
        PI03.kvalheim.net:
        PI04.kvalheim.net:
        PI08.kvalheim.net:
        
      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible
    
    crit:
      hosts:
        PI05.kvalheim.net:
        PI06.kvalheim.net:
        #PI07.kvalheim.net:

      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible

    rack_1:
      hosts:
        PI01.kvalheim.net:
        PI02.kvalheim.net:
        PI03.kvalheim.net:
        PI04.kvalheim.net:
      
      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible
    
    rack_2:
      hosts:
        PI05.kvalheim.net:
        PI06.kvalheim.net:
        #PI07.kvalheim.net:
        PI08.kvalheim.net:
      
      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_pass: pi06ansible

