---
- name: Install progs
  hosts: all
  remote_user: pi
  become: true
  vars: 
    file_path: /etc/snmp/snmpd.conf
           

  tasks:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes


    - name: Install SNMPD packages
      apt:
        name: snmpd
        state: latest
    
    - name: Install SNMP packages
      apt:
        name: snmp
        state: latest

    - name: Enable SNMP service
      service: name=snmpd enabled=yes
      notify: Restart snmpd

    - name: Remove localhost from SNMP Config
      lineinfile:
        path: "{{file_path}}"
        regexp: '^agentAddress  udp:127.0.0.1:161'
        line: '#agentAddress  udp:127.0.0.1:161'
      
    - name: Configure SNMP to listen on all interfaces
      lineinfile:
        path: "{{file_path}}"
        regex: '^#agentAddress udp:161'
        line: 'agentAddress udp:161,udp6:[::1]:161'

    - name: Configure SNMP public community
      lineinfile:
        path: "{{file_path}}"
        insertafter: '^#rocommunity public'
        line: 'rocommunity public 192.168.0.0/16'
  
    - name: Configure SNMP syslocation
      lineinfile:
        path: "{{file_path}}"
        regex: '^sysLocation'
        line: 'sysLocation Kirsebærhagen 23, 4055 Sola , Norway'
    
    - name: Configure SNMP syscontact
      lineinfile:
        path: "{{file_path}}"
        regex: '^sysContact'
        line: 'sysContact Geir Kvalheim <geir@kvalheim.net>'

    - name: Add extended snmp  1
      lineinfile:
        path: "{{file_path}}"
        line: extend hardware '/bin/cat /sys/firmware/devicetree/base/model'
    
    - name: Add extended snmp 2
      lineinfile:
        path: "{{file_path}}"
        line: extend serial '/bin/cat /sys/firmware/devicetree/base/serial-number'


    - name: Restart SNMP service
      service: name=snmpd enabled=yes
      notify: Restart snmpd