---
- name: Install progs
  hosts: rack_1
  remote_user: pi
  become: true
  vars: 
   
  tasks:

    - name: Shutdown servers {{item}}
      community.general.shutdown:
        delay: 60
        msg: 'Shutdown by Ansible'


    